# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '31 * * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-issue-stale: 60
        days-before-issue-close: 7
        stale-issue-message: 'This issue is marked as `stale` because there was no activity for 60 days. If the issue stays inactive, it will be closed in a week.'
        stale-issue-label: 'stale'
        close-issue-message: 'This issue has been closed due to inactivity.'

        days-before-pr-stale: 90
        days-before-pr-close: 30
        stale-pr-message: 'This pull request is marked as `stale` because there was no activity for 90 days. If the pull request stays inactive, it will be closed automatically in 30 days.'
        stale-pr-label: 'stale'
        close-pr-message: 'This pull request has been closed due to inactivity.'
